language: python
python:
  - "3.6"

matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true

install:
  - pip install -r requirements-dev.txt
  - if [[ $TRAVIS_PYTHON_VERSION == '3.6' ]]; then pip install black; fi
  - pip install -e .

script:
  - ./setup.py test --pytest-args="--cov-report= --cov=litecli"
  - coverage report
  - if [[ $TRAVIS_PYTHON_VERSION == '3.6' ]]; then ./setup.py lint; fi

after_success:
  - codecov

notifications:
  webhooks:
    urls:
      - YOUR_WEBHOOK_URL
    on_success: change # options: [always|never|change] default: always
    on_failure: always # options: [always|never|change] default: always
